# Generated by Django 4.1.2 on 2023-01-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_new',
            fields=[
                ('id_good', models.AutoField(primary_key=True, serialize=False)),
                ('name_good', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('amount', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'goods_new',
                'managed': False,
            },
        ),
    ]
