# Generated by Django 4.1.2 on 2023-01-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0002_goods_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods_new',
        ),
    ]
