# Generated by Django 4.1.2 on 2023-01-09 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0004_alter_goods_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='id_consignment',
            field=models.ForeignKey(blank=True, db_column='id_consignment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hardware_store.consignment'),
        ),
        migrations.AddField(
            model_name='goods',
            name='id_department',
            field=models.ForeignKey(blank=True, db_column='id_department', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hardware_store.department'),
        ),
        migrations.AddField(
            model_name='goods',
            name='id_producer',
            field=models.ForeignKey(blank=True, db_column='id_producer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hardware_store.producer'),
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
