# Generated by Django 4.1.2 on 2023-01-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0005_goods_id_consignment_goods_id_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='image2',
        ),
    ]
