# Generated by Django 4.1.2 on 2023-01-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_store', '0006_remove_goods_image2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'managed': False},
        ),
    ]
